### ISSUE TITLE
Please provide pre-generated API docs

### ISSUE THREAD

**Issue by ssokolow** [RockyTV/musicbrainz.rs#1]
While I assume you don't consider this ready to be uploaded to crates.io and docs.rs yet, one of the first things I want to look at when evaluating whether a crate is even related to my goals is the API.

(ie. Downloading and running rustdoc myself is unsuitable, because I want the rustdoc output to decide whether it's worth my time to download it.)

Would you mind at least putting up some manually-generated `rustdoc` output via GitHub Pages?

**Comment by Xinayder** [comment]
Nice to see someone interested in the crate! Anyways, there are indeed pre-generated API docs, which are generated every time a commit is pushed to `master`. It's available on https://rockytv.github.io/musicbrainz.rs

I'll update the README and I should really work some tiny bits on the library again.

EDIT: feel free to work on anything you'd like and submit a PR 😄

**Comment by ssokolow** [comment]
> Nice to see someone interested in the crate! Anyways, there are indeed pre-generated API docs, which are generated every time a commit is pushed to master. It's available on https://rockytv.github.io/musicbrainz.rs

Good to know.

> I'll update the README

Thanks. :)

> EDIT: feel free to work on anything you'd like and submit a PR 😄

Unfortunately, at the moment, I'm in one of those annoying situations where I have to get it done fast, sacrificing as much correctness and maintainability as necessary to meet that time requirement. ...so I'll probably have to use [python-musicbrainzngs](https://github.com/alastair/python-musicbrainzngs) for the prototype and put this on my TODO list for when the relevant project gets its turn in my "rewrite everything in Rust for better maintainability" push.

(As-is, the current state of this crate appears to be unsuitable for retrieving all of the fields (including embedded cover art) that [whipper](https://github.com/JoeLametta/whipper/) neglected to set in my FLAC files, and I can't afford to burn several dozen gigs of DVD+Rs now, only to replace them with proper ones later.)
